"""Plot layered soil-column results in the style used by soil-rock-dyn2.docx.

The reference document compares FLAC and MPM velocity histories using a
plain white axes box, red reference curves, and green dashed MPM curves.
This script applies that presentation to the current CSV data generated by
``layered_soil_column_shear_wave.py``.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[3]
RESULT_DIR = ROOT / "example/mpm/FLAC3D/results/layered_soil_column_shear_wave"
FT = 0.3048


def read_histories(path: Path) -> dict[str, np.ndarray]:
    with path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    return {
        key: np.array([float(row[key]) for row in rows], dtype=float)
        for key in rows[0]
    }


def shifted_signal(t: np.ndarray, signal: np.ndarray, delay: float) -> np.ndarray:
    return np.interp(t - delay, t, signal, left=0.0, right=0.0)


def reference_histories(data: dict[str, np.ndarray], diagnostics: dict[str, object]) -> dict[str, np.ndarray]:
    """Build an undamped 1D impedance-transfer reference from current input."""
    t = data["time"]
    vin = data["input_vx"]
    materials = diagnostics["materials"]  # type: ignore[index]
    h = float(diagnostics["H_m"])
    cs1 = float(materials["material_1"]["Cs"])  # type: ignore[index]
    cs2 = float(materials["material_2"]["Cs"])  # type: ignore[index]
    z1 = float(materials["material_1"]["rho"]) * cs1  # type: ignore[index]
    z2 = float(materials["material_2"]["rho"]) * cs2  # type: ignore[index]

    def travel_time_to_z(z: float) -> float:
        depth_target = h - z
        total = 0.0
        current_depth = h
        for d0, d1, cs in (
            (160.0 * FT, 80.0 * FT, cs1),
            (80.0 * FT, 40.0 * FT, cs2),
            (40.0 * FT, 0.0, cs1),
        ):
            upper = max(depth_target, d1)
            if current_depth > upper:
                total += (current_depth - upper) / cs
                current_depth = upper
            if current_depth <= depth_target + 1.0e-12:
                break
        return total

    def transfer_amplitude_to_z(z: float) -> float:
        depth = h - z
        amp = 1.0
        if depth < 80.0 * FT:
            amp *= 2.0 * z1 / (z1 + z2)
        if depth < 40.0 * FT:
            amp *= 2.0 * z2 / (z1 + z2)
        if abs(z - h) < 1.0e-12:
            amp *= 2.0
        return amp

    points = {
        "bottom_vx": 0.0,
        "lower_interface_depth_80ft_vx": h - 80.0 * FT,
        "upper_interface_depth_40ft_vx": h - 40.0 * FT,
        "middle_vx": 0.5 * h,
        "top_vx": h,
    }
    reference = {"bottom_vx": vin.copy()}
    for name, z in points.items():
        if name == "bottom_vx":
            continue
        reference[name] = transfer_amplitude_to_z(z) * shifted_signal(t, vin, travel_time_to_z(z))
    return reference


def apply_docx_axes_style(ax) -> None:
    ax.tick_params(direction="in", top=True, right=True, length=6, width=0.8)
    for spine in ax.spines.values():
        spine.set_linewidth(0.8)
    ax.grid(False)
    ax.set_facecolor("white")


def save_comparison(t: np.ndarray, reference: np.ndarray, mpm: np.ndarray, labels: tuple[str, str], out: Path) -> None:
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "font.family": "Times New Roman",
        "font.size": 12,
        "axes.labelsize": 12,
        "xtick.labelsize": 12,
        "ytick.labelsize": 12,
        "legend.fontsize": 10,
    })
    fig, ax = plt.subplots(figsize=(6.4, 4.8), dpi=100)
    ax.plot(t, reference, color="red", linewidth=0.8, label=labels[0])
    ax.plot(t, mpm, color="#00cc00", linewidth=0.8, linestyle=(0, (6, 5)), label=labels[1])
    ax.set_xlim(0.0, max(0.36, float(t[-1])))
    ymax = max(float(np.max(np.abs(reference))), float(np.max(np.abs(mpm))), 1.0e-12) * 1.18
    ax.set_ylim(-ymax, ymax)
    ax.set_xlabel("Time [s]")
    ax.set_ylabel("Vel [m/s]")
    ax.legend(loc="upper right", frameon=False, markerfirst=False, handlelength=3.0)
    apply_docx_axes_style(ax)
    fig.tight_layout()
    fig.savefig(out)
    plt.close(fig)


def save_all_locations(data: dict[str, np.ndarray], reference: dict[str, np.ndarray], out: Path) -> None:
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "font.family": "Times New Roman",
        "font.size": 12,
        "axes.labelsize": 12,
        "xtick.labelsize": 12,
        "ytick.labelsize": 12,
        "legend.fontsize": 8,
    })
    t = data["time"]
    curves = [
        ("bottom", "bottom_vx"),
        ("80 ft depth", "lower_interface_depth_80ft_vx"),
        ("40 ft depth", "upper_interface_depth_40ft_vx"),
        ("top", "top_vx"),
    ]
    fig, ax = plt.subplots(figsize=(8.0, 4.8), dpi=120)
    colors = ["red", "blue", "#00aa00", "black"]
    for (label, key), color in zip(curves, colors):
        ax.plot(t, data[key], linewidth=0.9, color=color, label=f"MPM-{label}")
        ax.plot(t, reference[key], linewidth=0.7, color=color, linestyle=(0, (6, 5)), alpha=0.75, label=f"ref-{label}")
    ax.set_xlim(0.0, max(0.36, float(t[-1])))
    ymax = max(float(np.max(np.abs(data[key]))) for _, key in curves) * 1.15
    ax.set_ylim(-ymax, ymax)
    ax.set_xlabel("Time [s]")
    ax.set_ylabel("Vel [m/s]")
    ax.legend(loc="upper right", frameon=False, fontsize=8, ncol=2, markerfirst=False)
    apply_docx_axes_style(ax)
    fig.tight_layout()
    fig.savefig(out)
    plt.close(fig)


def main() -> None:
    data = read_histories(RESULT_DIR / "histories.csv")
    diagnostics = json.loads((RESULT_DIR / "diagnostics.json").read_text(encoding="utf-8"))
    reference = reference_histories(data, diagnostics)
    plot_dir = RESULT_DIR / "docx_style_plots"
    plot_dir.mkdir(parents=True, exist_ok=True)

    t = data["time"]
    save_comparison(
        t,
        reference["top_vx"],
        data["top_vx"],
        ("Reference-top", "MPM-top"),
        plot_dir / "docx_style_top_velocity.png",
    )
    save_comparison(
        t,
        reference["top_vx"],
        data["top_vx"],
        ("Reference-top", "MPM-top"),
        plot_dir / "same_form_top_velocity.png",
    )
    save_comparison(
        t,
        reference["bottom_vx"],
        data["bottom_vx"],
        ("Reference-bot", "MPM-bot"),
        plot_dir / "docx_style_bottom_velocity.png",
    )
    save_comparison(
        t,
        reference["bottom_vx"],
        data["bottom_vx"],
        ("Reference-bot", "MPM-bot"),
        plot_dir / "same_form_bottom_velocity.png",
    )
    save_all_locations(data, reference, plot_dir / "docx_style_velocity_by_depth.png")
    print(f"Wrote DOCX-style plots to {plot_dir}")


if __name__ == "__main__":
    main()
